<?xml version="1.0" encoding="utf-8"?>
<project basedir="." default="create-db" name="SOTest" xmlns:ivy="antlib:org.apache.ivy.ant">

    <path id="lib.path" location="lib"/>

<!--    <ivy:configurations>-->
<!--        <conf name="runtime" description=""/>-->
<!--    </ivy:configurations>-->

    <target name="get-dependencies">
        <mkdir dir="lib"/>
        <ivy:cachepath pathid="lib.path">
            <dependency org="org.hibernate.orm" name="hibernate-core" rev="6.6.11.Final"/>
            <!--            <dependency org="org.junit.jupiter" name="junit-jupiter" rev="5.11.4"/>-->
            <dependency org="org.junit.platform" name="junit-platform-launcher" rev="1.11.4"/>
            <dependency org="org.springframework.boot" name="spring-boot-starter-test" rev="3.4.4"/>
            <dependency org="org.springframework.boot" name="spring-boot-starter-jdbc" rev="3.4.4"/>
            <dependency org="org.springframework.boot" name="spring-boot-starter-web" rev="3.4.4"/>
            <dependency org="org.postgresql" name="postgresql" rev="42.7.5"/>
        </ivy:cachepath>
        <ivy:retrieve/>
    </target>

    <target name="create-db" depends="get-dependencies">
        <sql driver="org.postgresql.Driver"
             classpath="lib/postgresql-42.7.5.jar"
             url="jdbc:postgresql://localhost/postgres"
             userid="postgres"
             password="password"
             src="src/main/resources/create.sql"
             autocommit="on">
        </sql>
    </target>

    <target name="init-db" depends="create-db">
        <sql driver="org.postgresql.Driver"
             classpath="lib/postgresql-42.7.5.jar"
             url="jdbc:postgresql://localhost/postgres"
             userid="postgres"
             password="password"
             src="src/main/resources/init.sql">
        </sql>
    </target>

    <target name="init" depends="get-dependencies">
        <mkdir dir="build/classes"/>
    </target>

    <target name="compile" depends="init">
        <javac srcdir="src" includeantruntime="false" destdir="build/classes" classpathref="lib.path"/>
    </target>

    <target name="jar" depends="compile">
        <mkdir dir="build/jar"/>
        <jar destfile="build/jar/web.jar" basedir="build/classes">
            <manifest>
                <attribute name="Main-Class" value="com.prak.web.DBManager"/>
            </manifest>
        </jar>
    </target>

    <target name="run">
        <java jar="build/jar/web.jar" fork="true"/>
    </target>

</project>
