<?xml version="1.0" encoding="utf-8"?>
<project basedir="." default="run" name="web" xmlns:ivy="antlib:org.apache.ivy.ant" xmlns:jacoco="antlib:org.jacoco.ant">

    <property resource="src/main/resources/application.properties"/>

    <path id="lib.path" location="lib"/>

    <target name="get-dependencies">
        <mkdir dir="lib"/>
        <ivy:cachepath pathid="lib.path">
            <dependency org="org.hibernate.orm" name="hibernate-core" rev="6.6.11.Final"/>
            <dependency org="org.junit.platform" name="junit-platform-launcher" rev="1.11.4"/>
            <dependency org="org.springframework.boot" name="spring-boot-starter-test" rev="3.4.4"/>
            <dependency org="org.springframework.boot" name="spring-boot-starter-jdbc" rev="3.4.4"/>
            <dependency org="org.springframework.boot" name="spring-boot-starter-web" rev="3.4.4"/>
            <dependency org="org.apache.tomcat.embed" name="tomcat-embed-jasper" rev="10.1.18"/>
            <dependency org="org.glassfish.web" name="jakarta.servlet.jsp.jstl" rev="3.0.1"/>
            <dependency org="org.apache.commons" name="commons-io" rev="1.3.2"/>
            <dependency org="org.postgresql" name="postgresql" rev="42.7.5"/>
            <dependency org="org.testng" name="testng" rev="7.7.0"/>
            <dependency org="org.apache.commons" name="commons-lang3" rev="3.14.0"/>
            <dependency org="javax.servlet.jsp" name="jsp-api" rev="2.0"/>
        </ivy:cachepath>
        <ivy:retrieve/>
    </target>

    <taskdef uri="antlib:org.jacoco.ant" resource="org/jacoco/ant/antlib.xml">
        <classpath path="lib/jacocoant.jar"/>
    </taskdef>


    <target name="create-db" depends="get-dependencies">
<!--    <target name="create-db">-->
        <sql driver="org.postgresql.Driver"
             classpath="lib/postgresql-42.7.5.jar"
             url="jdbc:postgresql://localhost/webdb"
             userid="postgres"
             password="password"
             src="src/main/sql/create.sql"
             autocommit="on">
        </sql>
    </target>

    <target name="init-db" depends="create-db">
        <sql driver="org.postgresql.Driver"
             classpath="lib/postgresql-42.7.5.jar"
             url="jdbc:postgresql://localhost/webdb"
             userid="postgres"
             password="password"
             src="src/main/sql/init.sql">
        </sql>
    </target>


    <target name="init" depends="init-db">
        <mkdir dir="build/classes"/>
    </target>

    <target name="compile" depends="init">
<!--    <target name="compile">-->
        <javac srcdir="src/main" includeantruntime="false" destdir="build/classes" classpathref="lib.path"/>
        <copy todir="build/classes">
            <fileset dir="src/main/resources" includes="**/*"/>
        </copy>
    </target>

    <target name="jar" depends="compile">
        <mkdir dir="build/jar"/>
        <manifestclasspath property="manifest.cp" jarfile="build/jar/web.jar">
            <classpath>
                <fileset dir="lib" includes="*.jar"/>
<!--                <fileset dir="build/resources" includes="*"/>-->
            </classpath>
        </manifestclasspath>
        <war destfile="build/jar/web.jar" basedir="build/classes" webxml="">
            <manifest>
                <attribute name="Main-Class" value="com.prak.web.WebPrak"/>
                <attribute name="Class-Path" value="${manifest.cp}"/>
            </manifest>
            <fileset dir="src/main/resources">
                <include name="*"/>
            </fileset>
        </war>
    </target>

    <target name="run" depends="jar">
        <java jar="build/jar/web.jar" fork="true">
            <classpath>
                <fileset dir="build/" includes="*.properties"/>
            </classpath>
        </java>
    </target>


    <target name="init-tests" depends="init-db">
        <mkdir dir="build/tests"/>
        <mkdir dir="coverage"/>
    </target>

    <target name="compile-tests" depends="init-tests">
        <javac srcdir="src" includeantruntime="false" destdir="build/tests" debug="true" classpathref="lib.path"/>
        <copy todir="build/tests">
            <fileset dir="src/main/resources" includes="**"/>
        </copy>
    </target>

    <path id="cp">
        <fileset dir="lib" includes="*.jar"/>
    </path>
    <taskdef name="testng" classpathref="cp" classname="org.testng.TestNGAntTask"/>

    <target name="test" depends="compile-tests">
<!--    <target name="test">-->
        <jacoco:coverage>
            <testng classpathref="cp" forkjvm="true">
                <classpath location="build/tests"/>
                <classfileset dir="build/tests/com/prak/web" includes="*_test.class"/>
            </testng>
        </jacoco:coverage>

        <jacoco:report>
            <executiondata>
                <file file="jacoco.exec"/>
            </executiondata>

            <structure name="web">
                <classfiles>
                    <fileset dir="build/tests"/>
                </classfiles>
                <sourcefiles encoding="UTF-8">
                    <fileset dir="src/main/java"/>
                    <fileset dir="src/test/java"/>
                </sourcefiles>
            </structure>

            <html destdir="coverage"/>
        </jacoco:report>
    </target>
</project>
